services:
  mongodb:
    image: mongo:7
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
    ports:
      - 127.0.0.1:27017:27017

  chatter:
    build: .
    ports:
      - 127.0.0.1:8067:8000/tcp
      - 127.0.0.1:8067:8000/udp
    environment:
      MONGODB_URI: mongodb://mongodb:27017
      JWT_SECRET: ${JWT_SECRET:-change-me-in-production}
      KLIPY_API_KEY: your-klipy-key
      STEAM_API_KEY:
      SERVER_URL: yourdomain.com

    volumes:
      - uploads:/app/external
    depends_on:
      - mongodb
    restart: unless-stopped
    #labels:
    #Traefik reverse proxy example config
    #traefik.enable: "true"
    #traefik.http.routers.chatter.entrypoints: "your-https-entrypoint"
    #traefik.http.routers.chatter.rule: "Host(`yourdomain.com`)"
    #traefik.http.routers.chatter.tls.certResolver: "your-tls-resolver"
    #traefik.http.routers.chatter.tls: "true"

volumes:
  mongo_data:
  uploads:
